/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nashss.se.nonplayercharacter;

import com.nashss.se.nonplayercharacter.characters.*;
import com.nashss.se.nonplayercharacter.io.StringPrinter;
import com.nashss.se.nonplayercharacter.io.StringProvider;
import com.nashss.se.nonplayercharacter.io.mocks.MockStringPrinter;
import com.nashss.se.nonplayercharacter.io.mocks.MockStringProvider;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

class AppTest {

    @Test
    void appConstructor_addsCharactersToHost() {
        StringProvider input = new MockStringProvider(List.of("ignored, but needed to avoid exception"));
        StringPrinter output = new MockStringPrinter();

        Host host = new Host("The host");
        List<NonplayerCharacter> subordinates = List.of(new Echo(), new Mathy());


        App _app = new App(input, output, host, subordinates);

        Map<String, NonplayerCharacter> hostSubs = host.getCharacters();

        assertEquals(subordinates.size(), hostSubs.size(),
                "Expeted host to have same number of subordinates as those sent to App constructor.");

        for (NonplayerCharacter sub : subordinates) {
            assertSame(sub, hostSubs.get(sub.name()));
        }
    }
}